const DISPLAY = document.getElementById('display');
const OPERATORS = document.querySelectorAll('.operator');
const BUTTONS = document.querySelectorAll('button');
const NUMBERS = document.querySelectorAll('button:not(.operator, .operator-dot, .equal, .topbutton)');
const DOT = document.querySelector('.operator-dot');
const EQUAL = document.querySelector('.equal');
const CLEAR = document.querySelector('.topbutton:first-child');
const DELETEBUTTON = document.querySelector('.delete');
const POWERBUTTON = document.querySelector('.topbutton:last-child');
const HISTORYBUTTON = document.querySelector('.h');
var body = document.querySelector('body');
var calculator =  document.querySelector('.calculator');
var aHistory = [];
var operator;
var content;
var a;
var b;
var on;
var equalPressed;